# Generated by Django 4.2 on 2023-04-07 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='picture',
            new_name='file',
        ),
    ]
